/*
 * Copyright © 2017 SNLab and others. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

package org.opendaylight.maple.impl;

import org.opendaylight.controller.md.sal.binding.api.DataObjectModification;
import org.opendaylight.controller.md.sal.binding.api.DataTreeChangeListener;
import org.opendaylight.controller.md.sal.binding.api.DataTreeModification;
import org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.NetworkTopology;
import org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.TopologyId;
import org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.Topology;
import org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.TopologyKey;
import org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.Link;
import org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.Node;
import org.opendaylight.yangtools.yang.binding.DataObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.annotation.Nonnull;
import java.util.Collection;
import java.util.Date;

public class TopologyListener implements DataTreeChangeListener<NetworkTopology> {

    private final static Logger LOG = LoggerFactory.getLogger(TopologyListener.class);

    @Override
    public void onDataTreeChanged(@Nonnull Collection<DataTreeModification<NetworkTopology>> changes) {

        int i=0;
        for (DataTreeModification<NetworkTopology> change : changes) {
            DataObjectModification<NetworkTopology> rootNode = change.getRootNode();
            DataObjectModification.ModificationType type = rootNode.getModificationType();

            System.out.println(i+":"+type);


            if(type.equals(DataObjectModification.ModificationType.SUBTREE_MODIFIED)){
                TopologyKey topologyKey = new TopologyKey(new TopologyId("flow:1"));
                DataObjectModification<Topology> topo = rootNode.getModifiedChildListItem(Topology.class, topologyKey);

                if(topo!=null){
                    DataObjectModification.ModificationType type1 = topo.getModificationType();
                    System.out.println("type1:"+type1);
                    switch(type1){
                        case WRITE:
                            break;
                        case SUBTREE_MODIFIED:

                            Collection<DataObjectModification<? extends DataObject>> topochildren = topo.getModifiedChildren();
                            for (DataObjectModification<? extends DataObject> mc : topochildren) {
                                Class<? extends DataObject> mctype = mc.getIdentifier().getType();
                                if(mctype.equals(Node.class)){
                                    System.out.println("Node: type=" +mc.getModificationType());

                                } else if(mctype.equals(Link.class)){
                                    System.out.println("Link: type="+mc.getModificationType());
                                }
                                if(mc.getModificationType().equals(DataObjectModification.ModificationType.SUBTREE_MODIFIED)){
                                    Collection<DataObjectModification<? extends DataObject>> mcc = mc.getModifiedChildren();
                                    for (DataObjectModification<? extends DataObject> mccc : mcc) {
                                        System.out.println(mccc);
                                    }
                                }
                            }

                            break;
                        case DELETE:
                            break;
                    }
                } else {
                    LOG.error("Topology changed but not flow:1");
                }
            }
            LOG.warn(rootNode.getDataAfter().toString());
        }
        System.out.println(new Date().toString()+"\n");

    }

    private void nodeModified(DataObjectModification<Node> node) {
        DataObjectModification.ModificationType type = node.getModificationType();
        System.out.println("node modified type:"+type);
        switch(type){
            case DELETE:
                break;
            case SUBTREE_MODIFIED:
                Collection<DataObjectModification<? extends DataObject>> modifiednodes = node.getModifiedChildren();
                for (DataObjectModification<? extends DataObject> mn : modifiednodes) {

                }
                break;
            case WRITE:
                break;
        }
    }

}

/*


ingress=openflow:1:1
ingress=openflow:3:3
ingress=openflow:1:2
ingress=openflow:2:3
0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Link: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Source, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:1:1, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:1:1, attributes={}}}}}}}
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Destination, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)destination, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:2:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:2, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:2:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:2, attributes={}}}}}}}
Link: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Source, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@14e3d011, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@14e3d011, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@14e3d011, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:1:2, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:1:2, attributes={}}}}}}}
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Destination, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)destination, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@14e3d011, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@14e3d011, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:3:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@14e3d011, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:3, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:3:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:3, attributes={}}}}}}}
Link: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Source, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:2, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:2:3, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:2, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:2:3, attributes={}}}}}}}
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Destination, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)destination, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:1:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:1, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:1:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:1, attributes={}}}}}}}
Link: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Source, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:3:3, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:3:3, attributes={}}}}}}}
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Destination, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)destination, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:1:2, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@67cf60bd, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:1, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:1:2, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:1, attributes={}}}}}}}
Sat Apr 08 21:54:59 CST 2017

ingress=openflow:1:1
ingress=openflow:1:2
ingress=openflow:2:3
ingress=openflow:3:3
0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Link: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Source, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:2, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:2:3, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@276e4adb, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@276e4adb, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:2, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@276e4adb, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:2:3, attributes={}}}}}}}
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Destination, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)destination, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:1:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:1, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@276e4adb, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@276e4adb, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:1:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@276e4adb, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:1, attributes={}}}}}}}
Sat Apr 08 21:55:04 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Link: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Source, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:1:1, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:1:1, attributes={}}}}}}}
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Destination, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)destination, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:2:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:2, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:2:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:2, attributes={}}}}}}}
Link: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Source, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:1:2, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:1, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:1:2, attributes={}}}}}}}
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Destination, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)destination, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:3:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:3, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:3:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:3, attributes={}}}}}}}
Link: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Source, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:3:3, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-node, value=openflow:3, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)source-tp, value=openflow:3:3, attributes={}}}}}}}
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.link.attributes.Destination, domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)destination, modificationType=MERGE, childModification={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, modificationType=MERGE, childModification={}], (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, modificationType=MERGE, childModification={}]}], oldMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:1:2, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@5403bc7c, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:1, attributes={}}}}}, newMeta = MaterializedContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@7e6f079d, subtreeVersion=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, children={(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-tp, value=openflow:1:2, attributes={}}}, (urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node=ValueNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@626cc052, value=ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)dest-node, value=openflow:1, attributes={}}}}}}}
Sat Apr 08 21:55:04 CST 2017





0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Link: type=DELETE
Link: type=DELETE
Node: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPoint[key=TerminationPointKey [_tpId=Uri [_value=openflow:2:3]]], domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:2:3}], modificationType=DELETE, childModification={}], oldMeta = SimpleContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@c8b5896, data=ImmutableMapEntryNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:2:3}], value=[ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id, value=openflow:2:3, attributes={}}, ImmutableAugmentationNode{nodeIdentifier=AugmentationIdentifier{childNames=[(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref]}, value=[ImmutableLeafNode{nodeIdentifier=(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref, value=/(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:2}]/node-connector/node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:2:3}], attributes={}}]}], attributes={}}}, newMeta = null}}
Sat Apr 08 21:55:20 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPoint[key=TerminationPointKey [_tpId=Uri [_value=openflow:1:1]]], domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:1:1}], modificationType=DELETE, childModification={}], oldMeta = SimpleContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@21625d6f, data=ImmutableMapEntryNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:1:1}], value=[ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id, value=openflow:1:1, attributes={}}, ImmutableAugmentationNode{nodeIdentifier=AugmentationIdentifier{childNames=[(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref]}, value=[ImmutableLeafNode{nodeIdentifier=(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref, value=/(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:1}]/node-connector/node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:1:1}], attributes={}}]}], attributes={}}}, newMeta = null}}
Sat Apr 08 21:55:20 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Link: type=DELETE
Link: type=DELETE
Node: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPoint[key=TerminationPointKey [_tpId=Uri [_value=openflow:3:3]]], domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:3:3}], modificationType=DELETE, childModification={}], oldMeta = SimpleContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@c8b5896, data=ImmutableMapEntryNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:3:3}], value=[ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id, value=openflow:3:3, attributes={}}, ImmutableAugmentationNode{nodeIdentifier=AugmentationIdentifier{childNames=[(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref]}, value=[ImmutableLeafNode{nodeIdentifier=(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref, value=/(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:3}]/node-connector/node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:3:3}], attributes={}}]}], attributes={}}}, newMeta = null}}
Sat Apr 08 21:55:20 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPoint[key=TerminationPointKey [_tpId=Uri [_value=openflow:1:2]]], domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:1:2}], modificationType=DELETE, childModification={}], oldMeta = SimpleContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@21625d6f, data=ImmutableMapEntryNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:1:2}], value=[ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id, value=openflow:1:2, attributes={}}, ImmutableAugmentationNode{nodeIdentifier=AugmentationIdentifier{childNames=[(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref]}, value=[ImmutableLeafNode{nodeIdentifier=(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref, value=/(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:1}]/node-connector/node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:1:2}], attributes={}}]}], attributes={}}}, newMeta = null}}
Sat Apr 08 21:55:20 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPoint[key=TerminationPointKey [_tpId=Uri [_value=openflow:2:1]]], domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:2:1}], modificationType=DELETE, childModification={}], oldMeta = SimpleContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@c8b5896, data=ImmutableMapEntryNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:2:1}], value=[ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id, value=openflow:2:1, attributes={}}, ImmutableAugmentationNode{nodeIdentifier=AugmentationIdentifier{childNames=[(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref]}, value=[ImmutableLeafNode{nodeIdentifier=(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref, value=/(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:2}]/node-connector/node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:2:1}], attributes={}}]}], attributes={}}}, newMeta = null}}
Sat Apr 08 21:55:20 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPoint[key=TerminationPointKey [_tpId=Uri [_value=openflow:2:2]]], domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:2:2}], modificationType=DELETE, childModification={}], oldMeta = SimpleContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@c8b5896, data=ImmutableMapEntryNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:2:2}], value=[ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id, value=openflow:2:2, attributes={}}, ImmutableAugmentationNode{nodeIdentifier=AugmentationIdentifier{childNames=[(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref]}, value=[ImmutableLeafNode{nodeIdentifier=(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref, value=/(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:2}]/node-connector/node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:2:2}], attributes={}}]}], attributes={}}}, newMeta = null}}
Sat Apr 08 21:55:20 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPoint[key=TerminationPointKey [_tpId=Uri [_value=openflow:3:1]]], domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:3:1}], modificationType=DELETE, childModification={}], oldMeta = SimpleContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@c8b5896, data=ImmutableMapEntryNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:3:1}], value=[ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id, value=openflow:3:1, attributes={}}, ImmutableAugmentationNode{nodeIdentifier=AugmentationIdentifier{childNames=[(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref]}, value=[ImmutableLeafNode{nodeIdentifier=(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref, value=/(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:3}]/node-connector/node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:3:1}], attributes={}}]}], attributes={}}}, newMeta = null}}
Sat Apr 08 21:55:20 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=SUBTREE_MODIFIED
LazyDataObjectModification{identifier = org.opendaylight.yang.gen.v1.urn.tbd.params.xml.ns.yang.network.topology.rev131021.network.topology.topology.node.TerminationPoint[key=TerminationPointKey [_tpId=Uri [_value=openflow:3:2]]], domData = ChildNode{mod = NodeModification [identifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:3:2}], modificationType=DELETE, childModification={}], oldMeta = SimpleContainerNode{version=org.opendaylight.yangtools.yang.data.api.schema.tree.spi.Version@c8b5896, data=ImmutableMapEntryNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)termination-point[{(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id=openflow:3:2}], value=[ImmutableLeafNode{nodeIdentifier=(urn:TBD:params:xml:ns:yang:network-topology?revision=2013-10-21)tp-id, value=openflow:3:2, attributes={}}, ImmutableAugmentationNode{nodeIdentifier=AugmentationIdentifier{childNames=[(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref]}, value=[ImmutableLeafNode{nodeIdentifier=(urn:opendaylight:model:topology:inventory?revision=2013-10-30)inventory-node-connector-ref, value=/(urn:opendaylight:inventory?revision=2013-08-19)nodes/node/node[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:3}]/node-connector/node-connector[{(urn:opendaylight:inventory?revision=2013-08-19)id=openflow:3:2}], attributes={}}]}], attributes={}}}, newMeta = null}}
Sat Apr 08 21:55:21 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=DELETE
Sat Apr 08 21:55:21 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=DELETE
Sat Apr 08 21:55:21 CST 2017

0:SUBTREE_MODIFIED
type1:SUBTREE_MODIFIED
Node: type=DELETE
Sat Apr 08 21:55:21 CST 2017



 */
